BASE_BOX_IMAGE = "ubuntu/focal64"

# master node
CPUS_MASTER = 4
MEMORY_MASTER = 8192
IP_MASTER = "192.168.57.12"

# agent node
CPUS_AGENT = 2
MEMORY_AGENT = 4096
IP_AGENT = "192.168.57.11"

# Change to increase the number of workers
# AGENT_NODE_COUNT = 1

Vagrant.configure("2") do |config|
  # Master node
  config.vm.define "master" do |master|
    master.vm.box = BASE_BOX_IMAGE
    master.vm.hostname = "master-node"
    master.vm.network "private_network", ip: IP_MASTER
    master.vm.network "forwarded_port", guest: 6443, host: 6443
    master.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.cpus = CPUS_MASTER
      vb.memory = MEMORY_MASTER
    end
    master.vm.provision "shell", inline: <<-SHELL
      # Install K3s master
      export FLAGS="--write-kubeconfig-mode 644 --node-ip #{IP_MASTER} --node-external-ip #{IP_MASTER}"
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="$FLAGS" sh -
      cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
      sudo cp /etc/rancher/k3s/k3s.yaml /vagrant/k3s.yaml
    SHELL
  end

  # Agent node
  config.vm.define "agent" do |agent|
    agent.vm.box = BASE_BOX_IMAGE
    agent.vm.hostname = "agent-node"
    agent.vm.network "private_network", ip: IP_AGENT
    agent.vm.network "forwarded_port", guest: 3000, host: 3000
    agent.vm.network "forwarded_port", guest: 30000, host: 30000
    agent.vm.provider "virtualbox" do |vb|
      vb.name = "agent"
      vb.cpus = CPUS_AGENT
      vb.memory = MEMORY_AGENT
    end
    agent.vm.provision "shell", inline: <<-SHELL
      # Install K3s agent
      HOST="https://#{IP_MASTER}:6443"
      TOKEN=$(cat /vagrant/node-token)
      curl -sfL https://get.k3s.io | K3S_URL=$HOST K3S_TOKEN=$TOKEN sh -
      echo "Host: $HOST and Token: $TOKEN"
    SHELL
  end
end

# export KUBECONFIG=$PWD/k3s.yaml
# sudo journalctl -u k3s -f
# sudo /usr/local/bin/k3s-agent-uninstall.sh
# curl -sfL https://get.k3s.io | K3S_NODE_NAME=agent K3S_URL=$HOST K3S_TOKEN=$TOKEN sh -
    # Agent node

  #   (1..AGENT_NODE_COUNT).each do |i|
  #     config.vm.define "agent#{i}" do |agent|
  #       agent.vm.box = BASE_BOX_IMAGE
  #       # agent.vm.hostname = "agent#{i}.example.com"
  #       agent.vm.network "private_network", ip: "192.168.57.1#{i}"
  #       # agent.vm.network "forwarded_port", guest: 6443, host: 6443
  #       agent.vm.provider "virtualbox" do |vb|
  #         vb.name = "agent#{i}"
  #         vb.cpus = CPUS_AGENT
  #         vb.memory = MEMORY_AGENT
  #       end
  #       agent.vm.provision "shell", path: "agent.sh"
  #     end
  # end
