BASE_BOX_IMAGE = "ubuntu/focal64"

# master node
CPUS_MASTER = 4
MEMORY_MASTER = 8192

# agent node
CPUS_AGENT = 2
MEMORY_AGENT = 4096

# Change to increase the number of workers
AGENT_NODE_COUNT = 1

Vagrant.configure("2") do |config|
  # Master node
  config.vm.define "master" do |master|
    master.vm.box = BASE_BOX_IMAGE
    master.vm.hostname = "master-node"
    master.vm.network "private_network", ip: "192.168.57.13"
    master.vm.network "forwarded_port", guest: 6443, host: 6443
    master.vm.network "forwarded_port", guest: 3000, host: 3000
    master.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.cpus = CPUS_MASTER
      vb.memory = MEMORY_MASTER
    end
    master.vm.provision "shell", inline: <<-SHELL
      # Install K3s master
      curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
      cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
    SHELL
  end

  # Agent node
  config.vm.define "agent" do |agent|
    agent.vm.box = BASE_BOX_IMAGE
    agent.vm.hostname = "agent-node"
    agent.vm.network "private_network", ip: "192.168.57.14"
    agent.vm.provider "virtualbox" do |vb|
      vb.name = "agent"
      vb.cpus = CPUS_AGENT
      vb.memory = MEMORY_AGENT
    end
    agent.vm.provision "shell", inline: <<-SHELL
      # Install K3s agent
      HOST="https://192.168.57.13:6443"
      TOKEN=$(cat /vagrant/node-token)
      curl -sfL https://get.k3s.io | K3S_URL=$HOST K3S_TOKEN=$TOKEN sh -
      echo "Host: $HOST"
      echo "Token: $TOKEN"
    SHELL
  end
end
    # Agent node

  #   (1..AGENT_NODE_COUNT).each do |i|
  #     config.vm.define "agent#{i}" do |agent|
  #       agent.vm.box = BASE_BOX_IMAGE
  #       # agent.vm.hostname = "agent#{i}.example.com"
  #       agent.vm.network "private_network", ip: "192.168.57.1#{i}"
  #       # agent.vm.network "forwarded_port", guest: 6443, host: 6443
  #       agent.vm.provider "virtualbox" do |vb|
  #         vb.name = "agent#{i}"
  #         vb.cpus = CPUS_AGENT
  #         vb.memory = MEMORY_AGENT
  #       end
  #       agent.vm.provision "shell", path: "agent.sh"
  #     end
  # end
