-- Create the rabbit user if it doesn't exist
DO
$do$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = :BILLING_DB_USER) THEN

      CREATE USER :BILLING_DB_USER WITH PASSWORD ':BILLING_DB_PASSWORD' SUPERUSER;
   END IF;
END
$do$;

SELECT 'CREATE DATABASE :BILLING_DB_NAME'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = :BILLING_DB_NAME)\gexec

-- Connect to the orders database
\c :BILLING_DB_NAME

CREATE TABLE IF NOT EXISTS public.orders (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  number_of_items INTEGER NOT NULL,
  total_amount NUMERIC(10, 2) NOT NULL
);

GRANT ALL PRIVILEGES ON DATABASE :BILLING_DB_NAME TO :BILLING_DB_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO :BILLING_DB_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO :BILLING_DB_USER;

-- Ensure future tables get the same permissions
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO :BILLING_DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO :BILLING_DB_USER;
