apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: k3s-agent
      containers:
      - name: billing
        image: antikaz/orcs:billing
        ports:
          - containerPort: 5000
        envFrom:
          - secretRef:
              name: billing-secret
        # resources:
        #   requests:
        #     cpu: "300m"
        #     memory: "256Mi"
        #   limits:
        #     cpu: "800m"
        #     memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: billing
spec:
  selector:
    app: billing
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

