apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-db
spec:
  serviceName: "billing-db"
  replicas: 1
  selector:
    matchLabels:
      app: billing-db
  template:
    metadata:
      labels:
        app: billing-db
    spec:
      nodeSelector:
        kubernetes.io/hostname: agent-node
      containers:
        - name: billing-db
          image: antikaz/orcs:billing-db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: billing-db-storage
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: billing-secret
  volumeClaimTemplates:
    - metadata:
        name: billing-db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: billing-db
spec:
  selector:
    app: billing-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432