apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-db
spec:
  serviceName: "inventory-db"
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: agent-node
      containers:
        - name: inventory-db
          image: antikaz/orcs:inventory-db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: inventory-db-storage
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: inventory-secret
  volumeClaimTemplates:
    - metadata:
        name: inventory-db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-db
spec:
  selector:
    app: inventory-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432