-- Create the user if it doesn't exist and set the password
DO
$do$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = :INVENTORY_DB_USER) THEN

      CREATE USER :INVENTORY_DB_USER WITH PASSWORD ':INVENTORY_DB_PASSWORD' SUPERUSER;
   END IF;
END
$do$;

-- Create the database if it doesn't exist
SELECT 'CREATE DATABASE :INVENTORY_DB_NAME'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = :INVENTORY_DB_NAME)\gexec

-- Connect to the inventory database
\c :INVENTORY_DB_NAME

CREATE TABLE IF NOT EXISTS public.movies (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL
);

GRANT ALL PRIVILEGES ON DATABASE :INVENTORY_DB_NAME TO :INVENTORY_DB_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO :INVENTORY_DB_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO :INVENTORY_DB_USER;

-- Ensure future tables get the same permissions
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO :INVENTORY_DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO :INVENTORY_DB_USER;
